baseURL = 'http://vamsi.blog/'
languageCode = 'en-us'
title = 'vamsi.blog'
theme = "hugo-bearblog"
author = "Vamsi Peri"
copyright = "Copyright © 2020, Jane Doe."
ignoreErrors = ["error-disable-taxonomy"]
disableKinds = ["taxonomy"]

[params]
  subtitle = "On Engineering Leadership, Generative Art and Books"
  description = "Hugo + Bear = :heart:"
  disableDisqusTypes = ["page"]
  hideMadeWithLine = true

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"
