baseURL = 'http://vamsi.blog/'
languageCode = 'en-us'
title = 'vamsi.blog'
theme = "hugo-ink"

paginate = 5

copyright = "© Vamsi Peri"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	subtitle = "On Engineering Leadership, Generative Art and Books"

	# Optional 64x64 avatar image.
	# avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"
    avatar = "https://i.postimg.cc/Gtx69gqb/2021-12-25-09-06-58-1.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "To Do"
url = "/todo"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/perivamsi"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
